In [1]:
import Util.ExploratoryDataAnalysis
import Util.ModelDevelopment
from pathlib import Path
import pandas as pd

In [11]:
data_dir = Path("data")

dfs = [
    Util.ExploratoryDataAnalysis.load_battles_file_to_df(file)
    for file in data_dir.glob("*.json")
]

df = pd.concat(dfs, ignore_index=True)

df = pd.get_dummies(df, columns=['result'])

print(df.shape)
df.head()

(223544, 28)

,battleTime,gameModeId,playerTag,opponentTag,playerCrowns,opponentCrowns,crown_diff,p_card_1,o_card_1,p_card_2,...,o_card_6,p_card_7,o_card_7,p_card_8,o_card_8,p_card_9,o_card_9,result_draw,result_loss,result_win
0,20260303T044817.000Z,72000006,#9CVVPULRY,#9RRRV9PLP,1,0,1,26000007,26000017,26000011,...,26000004,26000021,26000043,28000007,28000011,159000000,159000000,0,0,1
1,20260303T040122.000Z,72000006,#9CVVPULRY,#2200YRUGGU,3,0,3,26000007,27000013,26000011,...,28000026,26000021,28000013,28000007,26000101,159000000,159000000,0,0,1
2,20260303T035814.000Z,72000006,#9CVVPULRY,#VYGPRCQLJ,0,1,-1,26000007,26000011,26000011,...,28000004,26000021,26000021,28000007,28000001,159000000,159000000,0,1,0
3,20260303T034754.000Z,72000006,#9CVVPULRY,#2LRLG2C28,1,0,1,26000007,26000064,26000011,...,26000048,26000021,28000003,28000007,26000042,159000000,159000000,0,0,1
4,20260303T034441.000Z,72000006,#9CVVPULRY,#8UJQQCQR,1,0,1,26000007,26000007,26000011,...,28000015,26000021,26000005,28000007,26000044,159000000,159000000,0,0,1

In [12]:
# Get the list of all the cards in the game from Clash Royale API
cards_df = Util.ExploratoryDataAnalysis.fetch_all_cards()

display(cards_df)

,name,id,maxLevel,maxEvolutionLevel,elixirCost,rarity,is_support
0,Knight,26000000,16,3.0,3.0,common,False
1,Archers,26000001,16,1.0,3.0,common,False
2,Goblins,26000002,16,2.0,2.0,common,False
3,Giant,26000003,14,2.0,5.0,rare,False
4,P.E.K.K.A,26000004,11,1.0,7.0,epic,False
...,...,...,...,...,...,...,...
120,Vines,28000026,11,NaN,3.0,epic,False
121,Tower Princess,159000000,16,NaN,NaN,common,True
122,Cannoneer,159000001,11,NaN,NaN,epic,True
123,Dagger Duchess,159000002,8,NaN,NaN,legendary,True
124,Royal Chef,159000004,8,NaN,NaN,legendary,True

In [14]:
X, y, artifacts = Util.ModelDevelopment.build_features_and_target(df, cards_df, n_cards_per_side=9, return_artifacts=True)

print(X.shape)
X.head()

(223544, 267)

,gameModeId,hour,day_of_week,p_has_26000000,p_has_26000001,p_has_26000002,p_has_26000003,p_has_26000004,p_has_26000005,p_has_26000006,...,p_building_count,o_avg_elixir,o_total_elixir,o_troop_count,o_spell_count,o_building_count,avg_elixir_diff,spell_diff,building_diff,troop_diff
0,72000006,4,1,0,0,0,0,0,0,0,...,1,4.714286,33.0,5,3,0,-1.339286,-1,1,0
1,72000006,4,1,0,0,0,0,0,0,0,...,1,4.000000,32.0,4,2,2,-0.625000,0,-1,1
2,72000006,3,1,0,0,0,0,0,0,0,...,1,3.125000,25.0,6,2,0,0.250000,0,1,-1
3,72000006,3,1,0,0,0,0,0,0,0,...,1,4.750000,38.0,7,1,0,-1.375000,1,1,-2
4,72000006,3,1,0,0,0,0,0,0,0,...,1,4.000000,32.0,7,1,0,-0.625000,1,1,-2